// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Siteimprove.UI.MonoTest {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected Test.UI.Button buttonWithData;
		
		protected Test.UI.Button Button2;
		
		protected Test.UI.Button Button4;
		
		protected Test.UI.Button Button6;
		
		protected Test.UI.LinkButton LinkButton1;
		
		protected Test.UI.Grid TableView1;
		
		protected Test.UI.Column Column1;
		
		protected Test.UI.Grid TableView2;
	}
}
